from typing import Any, Callable, List

def translate_pattern(
    pattern: str,
    editorconfig_braces: bool = False,
    editorconfig_asterisk: bool = False,
    editorconfig_double_asterisk: bool = False,
) -> str: ...
def make_matcher(pattern: str, **kwargs: Any) -> Callable[[str], bool]: ...
def match(pattern: str, path: str, **kwargs: Any) -> bool: ...
def filter(patterns: List[str], paths: List[str], **kwargs: Any) -> List[str]: ...
def find(
    patterns: List[str], root: str, paths: List[str] = None, **kwargs: Any
) -> List[str]: ...
